- cli.js
- index.js
this way the app will be able to register itself to be able to handle `magnet` links etc. should probably be exposed in the cli as well
> add custom protocol handler support

- linux.js
- mac.js
- package.json
`electron-packager . MyApp --asar`
Thanks!
> Add asar support. Closes GH-2

- mac.js
- readme.md
It's a start. Starting to get ugly with all them callbacks though. :)
https://github.com/maxogden/electron-packager/issues/16
> Added --sign to mac

- linux.js
- mac.js
- win32.js
see https://github.com/maxogden/electron-packager/pull/42#issuecomment-104022884
> always dereference symlinks - per #42

- win32.js
https://github.com/maxogden/electron-packager/issues/44
> convert slashes on windows so unix-format ignores work

- readme.md
Added API section to readme and updated the text about `--ignore`
fixes https://github.com/maxogden/electron-packager/issues/27 and https://github.com/maxogden/electron-packager/issues/41
:swimmer:
> Docs improvements

- CONTRIBUTING.md
Ask people for their platform and target platform when reporting issues, since that helps in identifying which code might be responsible.
> Update CONTRIBUTING.md :book: :wink:

- readme.md
Add example for ignoring multiple folders
> update readme with example for ignoring multiple directories

- common.js
- index.js
- linux.js
- mac.js
- win32.js
Moves a few common functions to their own module, plus some code cleanup I noticed while I was moving things around.
> Deduplicate code + cleanup

- linux.js
- mac.js
- win32.js
> get rid of source dir in path for ignore filter matching

- mac.js
currently just fails silently :(
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maxogden/electron-packager/99)
> fix(mac): handle spaces when signing

- index.js
- readme.md
- usage.txt
Possible PR for #112 but might need some doc changes.
> Pipe optional cache option to electron-download

- readme.md
:wave: 
You're sitting right next to me and saw me type these things so I hope you like it :pizza: :cat2:
> Document Icon Filetypes 

- readme.md
- usage.txt
* Reworded a bunch of things
* Removed the duplicate CLI usage section, added a link to usage.txt
* More consistent formatting
I'll rebase before this gets merged.
> Documentation cleanup

- cli.js
- index.js
- readme.md
- usage.txt
passes it onto electron-download
> Add strict-ssl option

- mac.js
cf. #219 for the issue & research :star2:
> Don't declare helper app as a protocol handler. Closes #219

- .gitignore
- .travis.yml
- package.json
- readme.md
> Add coveralls support

- CONTRIBUTING.md
> Add preamble and pull request sections to the contributing docs

- mac.js
- package.json
The new version solves a number of bugs where dylibs are not all signed
> Update osx sign

- readme.md
- usage.txt
> Split up arguments section into OS-specific subsections

- mac.js
- test/mac.js
Continue work of @psxjpc on resolving #195 by fixing coding style issues and adding a unit test.
Closes #244.
> Fix OSX Binary Names (continuation of #244)

- common.js
- test/basic.js
This is #298 but with an extra unit test to make sure it works with Electron 0.37.4.
> Delete default_app.asar in Electron >= 0.37.4

- package.json
fix https://github.com/atom/rcedit/pull/11
> Update rcedit to 0.5

- docs/api.md
- usage.txt
> asar-unpack: mention multiple directory support in documentation

- docs/api.md
- index.js
- test/hooks.js
- test/index.js
Closes #354.
CC: @MarshallOfSound
> Add afterExtract hook

- CONTRIBUTING.md
- NEWS.md
- common.js
- index.js
- issue_template.md
- mac.js
- package.json
- win32.js
This will make it way easier to get system information out of a user who reports an issue _(in theory)_.
> Add basic debug support via the 'debug' module

- readme.md
:white_check_mark: 
Made the fiel trees in readme.md more readable based on the output of command `tree`.
I only changed the readme file.
No code change -> The same like before.
Didn't executed because I changed the readme file.
> Make file trees more readable

- .travis.yml
- common.js
- index.js
Yuppers
Increasing the debug output on Travis to try and troubleshoot a recent timeout there:
```
Packaging app for platform linux x64 using electron v0.35.6
not ok 19 test timed out after 30000ms
---
operator: fail
...
```
https://travis-ci.org/electron-userland/electron-packager/jobs/154204776
It does not appear related to the recent `wine` usage on macOS since it is building a linux target from a mac host so `rcedit` shouldn't be used.
N/A
N/A
**Does the testsuite pass successfully on …
> Debug Travis CI failures

- common.js
Yup Yup
Adds a few more `debug` logs when moving and renaming the app to debug flaky test failures on Travis CI.
Trying to get a sense of what is happening/has already happened when the tests timeout.
Yes
Yes
Yes
> Add more debug logging

- package.json
Yes
Upgrade to `electron-download@3.0` which includes `SHASUM256.txt` checking.
Refs https://github.com/electron-userland/electron-download/pull/25
None needed.
Yes
Yes
> Upgrade to electron-download@3.0 for SHASUM256.txt checking

- targets.js
- test/basic.js
Yes.
Validate that arch/platform is not passed anything but an Array or a String, and generate an Error to that effect when invalid. Addresses #533.
Already documented.
Yes.
Yes.
> Better type checking when validating arch/platform

- common.js
- docs/api.md
- index.js
- mac.js
- package.json
- test/asar.js
- test/basic.js
- test/cli.js
- test/darwin.js
- test/hooks.js
- test/mac.js
- test/mas.js
- test/multitarget.js
- test/util.js
- test/win32.js
- usage.txt
Yes
Addresses the first point in the spec described in #154.
Yes
Yes
Yes
> Add electronVersion option & deprecate version

- NEWS.md
- common.js
- index.js
> Add CLI option name to deprecatedParameter message

- docs/api.md
- usage.txt
> Clarify derefSymlinks docs

- package.json
- test/util.js
Mostly for future PRs. Amazingly enough, there was only one weird linting error and one that needed to get disabled.
> Add eslint-plugin-tape for tape test linting

- index.js
- test/basic.js
> Prevent app names ending with " Helper"

- package.json
Update `eslint-config-standard`, although version 8 is coming out soon.
> Upgrade eslint-config-standard to 7.0.0

- test/mac.js
* ~~The changes are appropriately documented~~ (not applicable).
ES2015ify and DRY up the macOS tests.
> Clean up macOS tests

- NEWS.md
- targets.js
- test/targets.js
> Allow spaces for string-based arch/platform lists

- NEWS.md
- common.js
- docs/api.md
- mac.js
- test/basic.js
- test/mac.js
- test/util.js
- usage.txt
> Add extraResource support to all platforms

- SUPPORT.md
- docs/faq.md
- issue_template.md
- readme.md
Adds frequently asked questions!
> Add initial FAQ

- .travis.yml
- test/ci/appveyor.yml
Electron Packager only supports [Node versions which are supported the Node.js team](https://github.com/nodejs/Release), particularly when testing via CI.
> Only test against supported Node versions

- readme.md
This should make it easier to find information from the readme.
> Add a table of contents to the readme

- readme.md
I have added electron-packager-languages in README since we had a conversation in #767
Closes #767.
> Add electron-packager-languages in README

- package.json
fs-extra 5 has support for Node 8+'s native `fs.copyFile`, which should help with performance with large apps.
Closes #762.
> Upgrade fs-extra to ^5

- package.json
This should fix the "Unable to set icon" problems people were reporting previously. _(Does not necessarily mean that future instances of this error will be fixed by it.)_
> Upgrade rcedit to 1.0.0

- cli.js
> Use semver to check the Node version in the CLI

- test/_util.js
- test/asar.js
- test/basic.js
- test/darwin.js
- test/ignore.js
- test/mas.js
- test/prune.js
- test/win32.js
* ~~The changes are appropriately documented~~ (not applicable).
Deduplicate code and make the tests more readable.
> Test refactors

- readme.md
Add a link to `electron-installer-windows` project to the README
> Add link to electron-installer-windows

- package.json
- test/_util.js
- test/asar.js
- test/basic.js
- test/darwin.js
- test/infer.js
- test/mas.js
Also:
* disable AVA's Babel support to speed up the testsuite
* consolidate `console.warn` testing methods
> Upgrade ava to ^1

- package.json
- platform.js
> Upgrade asar and yargs-parser dependencies

- common.js
- docs/api.md
- readme.md
- test/index.js
- usage.txt
Use the more recent term for the OS that Macs run :)
> docs: OS X => macOS

- test/_util.js
- test/asar.js
- test/basic.js
- test/darwin.js
- test/hooks.js
- test/ignore.js
- test/infer.js
- test/mas.js
- test/prune.js
- test/targets.js
- test/win32.js
Refactor the test helpers so that it's easier to isolate tests to run when developing.
> Refactor test helpers

- src/infer.js
- test/fixtures/infer-non-version-electron-prebuilt-compile/node_modules/electron-prebuilt-compile/package.json
- test/fixtures/infer-non-version-electron-prebuilt-compile/package.json
- test/infer.js
> Handle inference where electron-prebuilt-compile points to a non-version

- package.json
https://github.com/electron-userland/electron-notarize/compare/v0.0.5...v0.1.0
> chore: upgrade electron-notarize to ^0.1.0

- package.json
- src/win32.js
Upgrade to the promisified `rcedit` module.
> chore: upgrade rcedit to ^2.0.0

- .travis.yml
- package.json
- test/ci/before_install.sh
- test/cli.js
> chore: upgrade the ava ecosystem to ^2

- src/mac.js
> fix: handle the electron GPU helper error on mac

- NEWS.md
- src/index.js
> fix: symlink test regression

- src/infer.js
- test/fixtures/infer-missing-electron-version/package.json
- test/fixtures/infer-missing-name/package.json
- test/infer.js
#1079 inadvertently decreased test coverage. This PR fixes that.
> test: fix infer test coverage

- docs/api.md
- src/index.js
- test/basic.js
- usage.txt
> feat: add electronZipDir option

- .circleci/config.yml
- README.md
- package.json
- src/mac.js
- test/_util.js
- test/basic.js
- test/ci/before_install.sh
- test/infer.js
After #1121 got merged, we need to require Node 10 in the package and make sure that in the future, dependencies which require higher Node versions fail CI.
BREAKING CHANGE: drop support for Node < 10
> feat: require Node 10

- .eslintrc.typescript.js
- package.json
Upgrade to ESLint 7 with related TypeScript modules.
> build(deps-dev): upgrade eslint to ^7.1.0 & @typescript-eslint/* to ^3.0.0

- src/infer.js
- test/infer.js
> fix(infer): add missing fields to the infer error message

- .circleci/config.yml
Add Node 14 to the list of major Node versions to test in CI.
> build: test Node 14 in CI

- package.json
- src/common.js
Related to https://github.com/electron/get/pull/162
> refactor: replace sanitize-filename with filenamify

- README.md
- src/index.d.ts
- src/targets.js
- test/targets.js
:apple: Si
[Reference](https://twitter.com/MarshallOfSound/status/1286054060424978432)
> feat: add darwin/arm64 and mas/arm64 as official platform/arch combinations

- .github/workflows/docs.yml
Same as https://github.com/electron/get/pull/174
> ci: customize docs commit user & prevent CircleCI from running for gh-pages

- README.md
> docs(readme): update grammar

- src/cli.js
> fix: package should not log info on --quiet flag

- .circleci/config.yml
- .github/workflows/canary.yml
- .github/workflows/docs.yml
- package.json
This reverts commit c6b4c78210f589291188213a8c6e968b98e7c82e, allowing us to release a new version of packager before a breaking change.
> revert: "feat!: upgrade Node.js to 14 LTS (#1393)"

- .circleci/config.yml
- .github/workflows/canary.yml
- .github/workflows/docs.yml
- package.json
Relands #1393 after cutting a new version of packager with a fix for Electron 20.
> feat!: upgrade Node.js to 14 LTS

- src/index.d.ts
- test/index.test-d.ts
Adds a missing typing in https://github.com/electron/electron-packager/pull/1346.
> fix(types): add "universal" as a valid arch

- yarn.lock
As in title, small nested dependency bump
> build: bump dependencies to clean yarn audit

- .github/workflows/canary.yml
- .github/workflows/docs.yml
* Pins SHAs for actions
* Updates `actions/setup-node` to clear deprecation warnings on workflow runs
> build: update GitHub actions workflows

- .circleci/config.yml
> build: use CircleCI cimg/node images

- .github/workflows/docs.yml
Use a GitHub app to update the docs so we can better tighten down branch restrictions.
> ci: use GitHub app for commits

- README.md
The badge has been showing `Unknown` instead of the coverage data since the repo name change.
> chore: update Codecov badge

- package.json
- temp/targets.js
- yarn.lock
Temporary fix for https://github.com/electron/forge/issues/3443, this should be reverted once a new Forge version is released.
> fix: temporary shim for Forge

- src/resedit.ts
This caused weird issues with the memory address that the data was loaded from
> fix: do not deref the integrity buffer

- src/index.ts
Fixes #1700
Per our own docs this should work: https://github.com/electron/packager/blob/main/src/packager.ts#L187-L210
> fix: restore circular export to ease migration

- yarn.lock
Closes https://github.com/electron/packager/pull/1756
> build: upgrade `@electron/get`

- package.json
- yarn.lock
fix: `asar` operations that previously failed due to a broken @electron/asar import
> fix: Require @electron/asar@^3.2.13

- .github/workflows/canary.yml
- README.md
This PR updates references to `electron-quick-start` to the renamed repo `minimal-repro`
> chore: update electron-quick-start references

- package.json
> fix: add @malept/cross-spawn-promise to dependencies
