electron/packager

index.js
readme.md

Fixes GH-4.
When run with `--prune`, it'll run on `npm prune --production` on the app folder. Leaves the original directory's modules in tact.

Add prune option

---

index.js
readme.md

You can now pass an `--icon` argument to set a custom app icon. This would fix #5 but, without icns converstion.
```
atom-shell-packager ./app AppName --icon==resources/app.icns
```

add --icon support

---

index.js
readme.md

You can now pass an `--version` argument to set the app version.
```
atom-shell-packager ./app AppName --app-version=1.0.0
```

add --app-version support

---

index.js
linux.js
mac.js

This PR basically does two things:
* OS-specific code goes in its own file
* Adds basic Linux support, i.e., it generates a `dist` folder with a runnable app that can be tarballed or converted into a distro-specific package by some other tool.
Admittedly, I didn't test that my changes didn't cause any regressions when I ported the Mac code, as I don't own a Mac.
Addresses part of #3.

Basic Linux support

---

readme.md

Forgot to add the `asar` option to the readme. Thanks!

Add asar to readme

---

cli.js
index.js
package.json
windows.js

supports:
- input directory
- name
- asar
- prune
- icon
not implemented:
- protocols
- app-version

add windows support - #3

---

mac.js

The other OSes handle out directories that don't exist correctly.

Ensure the out dir specified exists when building OSX app

---

readme.md

grunt-electron is pretty dumb, but without it you have to do some useless boilerplate, so why not.

add `grunt-electron` to the readme

---

index.js

Currently electron-packager tries to download the electron archive with the given arch, no matter if the arch is valid or not.

Validate the --arch argument

---

index.js

Regardless of what the outcome in https://github.com/maxogden/electron-packager/issues/13 will be. I think we should ignore what @sindresorhus first suggested, the module itself and the related `electron-prebuilt` and even `.git`.
:construction_worker:

Ignore this and related modules

---

index.js

this fixes my case mentioned in https://github.com/maxogden/electron-packager/issues/44 - i had my project in a folder `/Users/zaggino/github/brackets-electron/` and `.git` matched the `/github` part

fix defaultIgnores to be proper reg-exps

---

mac.js

The packager strips quotes from the `--sign` argument, which makes using a more detailed signing identity (necesssary when having multiple identities for iPhone, Mac App Store and/or Deveoper ID) impossible.

Add quotes around signing identity to allow spaces

---

readme.md
win32.js

This PR fixes the following issue `Set product name, file description copyright on Windows`
https://github.com/maxogden/electron-packager/issues/30
As per the comment https://github.com/maxogden/electron-packager/issues/30#issuecomment-111472208 by @felicienfrancois, `rcedit`  is already doing it. 
This patch has following changes
- User need to pass `version-string` hash in the options. THis has following fields
```
CompanyName
LegalCopyright
FileDescription
OriginalFilename
FileVersion
ProductVersion
ProductName
InternalName
```
- instead of passing just the icon to rcedit, now the version-string is also passed.
Below the sample grunt config
```
electron:{
win : {
options: {
name : 'Fresenius',
dir : 'build/',
out : 'package/app/win32',
version : '0.25.3',
platform: 'win32',
arch : …
```

Version info added to the final executable using rcedit

---

mac.js

I put `moveDirectory` in `common.js` because it didn't seem like a OS-specific function.
Fixes #60.

Fix renaming folders across volumes (when packaging for OS X)

---

cli.js
linux.js
mac.js

Fixes https://github.com/maxogden/electron-packager/issues/39
Problem does not appear on Windows.
Tested on Mac. Would appreciate anyone to try this on linux.

Support `--overwrite` options

---

mac.js

This fixes the helper process showing up in Activity Monitor as "Electron Helper"; it will now show up as "<appname> Helper".
Fixes #65.

Fix #65: Rename Helper application on Mac OS X

---

common.js
linux.js
win32.js

This needs to be done when Windows is the host OS regardless of
the target platform, not vice versa.
Fixes #79.
Tested on Windows 7, OS X 10.10, and Xubuntu.

Fix path separator replacement for ignore on Windows

---

mac.js
test/mac.js
win32.js

This fixes #100 by renaming all 3 helper apps and their executables for OS X releases.  A new test is included.
This is a follow-up to #76, in which I'd only renamed the main helper app, because I wasn't seeing anything break even without renaming the other helpers, but #100 has proven otherwise.
There is one additional commit in this branch which fixes error reporting for win32 and darwin targets, which I apparently somehow goofed and missed in #88 I think.

Rename ALL the helpers

---

mac.js
readme.md
test/mac.js

Like in #93 i need to add the release and build version number for my OSX app. Unfortunately that PR wouldn't solve my problem cause i need to add a different build version.
Also the `app-version` is stored in the `CFBundleVersion ` property which is, according to [Apple](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html), meant to store the build version number, whereas the `CFBundleShortVersionString ` stores the actual release version. I would suggest to store the `app-version` in `CFBundleShortVersionString` and the new `build-version` in `CFBundleVersion`.
Besides that great project. Whole setup worked like a charm.

Add build version number for OSX

---

.travis.yml
common.js
readme.md
test/basic.js
test/fixtures/basic/file_to_unpack.pac
usage.txt

fixes #101 Integrated asar options for unpack and snapshot.
unpack can be used by passing the flag --asar-unpack
This option would enable users to unpack files to `app.asar.unpacked` directory. asar-unpack accepts regex string for referring the files to be unpacked

Add option to pass --unpack argument to asar

---

readme.md

Hello,
I got a strange bug using Electron's auto-update that turned out to be because I set the `build-version` option as an number while it should be a string (https://github.com/atom/electron/issues/3067).
This PR simply adds this information to the readme.

Add `build-version` to opts documentation

---

.travis.yml
package.json
test/index.js
test/win32.js
win32.js

I had trouble cleaning up my commit logs on previous pull request. I'm not sure how to put up a test for windows executable file version though.

Fix #129: support file-version metadata (win32)

---

test/win32.js
win32.js

This is basically a copy/paste solution from #143. Includes a test.
Attempts to fix #172.

[win32] Ensure product version is set on the executable

---

common.js
package.json
readme.md
test/basic.js
usage.txt

The lastest version(v0.8.2) of asar supports unpack directory, atom/asar#44. It's resonable to implement on electron-packager. 
Fixes #171, and part of #114(We can unpack the `PepperFlashPlayer.plugin` directory on OS X).

Support unpack directory

---

index.js
test/fixtures/basic/package.json

I'm not sure there's a good reason that `node_modules/.bin` should be packaged along with the rest of the app. Besides, it breaks if you use NPM 3 and `--prune` (for why, see https://github.com/maxogden/electron-packager/issues/180#issuecomment-152897559).
This should fix #149 and #180.

Ignore node_modules/.bin by default

---

common.js
test/basic.js

It should not be necessary to include Electron's default_app. (I've only tested this on Linux so far)
Fixes #49
Thanks for electron-packager!

Don't include default_app

---

readme.md

Descriptions based on summaries in `usage.txt`.
Fixes #175.

Document the rest of the optional arguments in the readme

---

readme.md
test/win32.js
usage.txt
win32.js

`app-version` and `build-version` take precedence over `version-string.ProductVersion` and `version-string.FileVersion`, respectively.
Closes #170. (Well, obsoletes it.)

Convert app-version and build-version to be cross-platform arguments

---

common.js
index.js
readme.md
test/basic.js
usage.txt

Custom temporary directory can be supplied in `opts.tmpdir` or from the command line switch `--tmpdir`.  This address issue #203.

adds `tmpdir` option to fix #203

---

common.js
index.js
readme.md
test/basic.js

This PR allows the `ignore` option to be a Function as well as a Regexp

Allow ignore to be a Function

---

mac.js
test/mac.js

Ensure that CFBundleVersion and CFBundleShortVersionString are
both stored as strings, even if the app-version or build-version
options are integers.
https://github.com/maxogden/electron-packager/issues/242

Simple fix for issue 242: Info.plist issues with CFBundleVersion

---

index.js
mac.js
package.json
readme.md
test/basic.js
test/config.json
test/darwin.js
test/fixtures/basic/package.json
test/index.js
test/mac.js
test/mas.js
test/multitarget.js
test/util.js
usage.txt

- MAS platform support
- Entitlements (optional) are supported to sign apps, not just with a certificate
- Made it easier to sign for MAS distribution, may fallback to default entitlements file

Platform: Mac App Store support

---

CONTRIBUTING.md
NEWS.md

As mentioned in https://github.com/maxogden/electron-packager/issues/235#issuecomment-170384955 and https://github.com/maxogden/electron-packager/pull/223#issuecomment-183989800.
Only contains changes from 5.2.0 onward. If someone else wants to backfill, feel free :grin:

Add NEWS.md, a human-readable list of changes

---

NEWS.md
readme.md
test/win32.js
usage.txt
win32.js

Deprecate `version-string.LegalCopyright`.
Fixes #265.

Add Windows support to app-copyright

---

common.js
index.js
package.json
readme.md
test/basic.js
test/util.js
test/win32.js

This pull request supersedes #155. And is required for #251.
Tests and doc added.

Automatically ignore --out path

---

common.js
index.js
package.json
readme.md
test/basic.js
test/util.js
test/win32.js

I use electron-packager programmatically in [electron-complete-builder](https://github.com/develar/electron-complete-builder).
Currently, electron-packager cannot be used in parallel —my tests failed (I use [ava](https://github.com/sindresorhus/ava)). Because electron-packager uses one predefined temp directory instead of random — `path.join(opts.tmpdir || os.tmpdir(), 'electron-packager')`
This pull request doesn't fix it. Instead, I ask you ability to disable using of temp dir. And just use specified   `out` directly.
Why?
* If you use programmatically, you maybe already manage temp dir. For example, temp dir and out dir management (overwrite check) is not required for `electron-complete-builder` — it is already implemented on my side. 
* In tests, you have to copy project directory to …

Ability to set tmpdir to false to disable using temp directory

---

mac.js
readme.md
test/fixtures/data1.txt
test/fixtures/extrainfo.plist
test/mac.js
usage.txt

It is useful to be able to set *arbitrary* fields in the plist file. MacOS documents many keys, and it's unreasonable to define a separate electron-packager argument for each one. Some keys also need large array or dict structures, which can't comfortably be specified on the command line or in a package script.
Therefore, we want to be able to specify a plist file and merge its contents into the app Info.plist.
We may also need to install files directly into the app's Contents/Resources directory. For example, `UTExportedTypeDeclarations` may specify an icon for a document type; the icon should be an .icns file in Contents/Resources.
Therefore, two new arguments:
`extend-info`: Take the filename of a plist file and extend Info.plist with its contents. Other explicit arguments such as …

Add `extend-info` and `extra-resource` arguments for creating the Mac application package.

---

mac.js
readme.md
usage.txt

Allows the `entitlements-inherit` option of `electron-osx-sign` to be passed.
Related to #271

Add option for child entitlements

---

package.json

Does this work? Also, want me not to bump electron-packager to 5.2.2?

Bump electron-download to v2

---

NEWS.md
cli.js
mac.js
readme.md
test/mac.js
usage.txt

Per discussion in #285, I feel that there are too many OS X signing options, and that it would be better to group them together. This has the added benefit of leaving in room for a potential future Windows signing module to be integrated (#32).
CC: @sethlu

Consolidate OSX signing params

---

mac.js
test/fixtures/el-0374/index.html
test/fixtures/el-0374/main.js
test/fixtures/el-0374/package.json
test/index.js
test/mac.js

https://github.com/electron-userland/electron-packager/issues/300
This is an easy fix. It writes the icon to the filename defined in CFBundleIconFile, so it will work in Electron 0.37.4 as well as earlier versions.
Since the test/config.json specifies "0.35.6", there's no way to test this fix directly. Is that okay, or should we figure out how to test both configurations? (If so, how?)

Fix for issue 300: --icon option does not work under Electron 0.37.4

---

package.json

Fixes warnings logged about graceful-fs deprecations. https://github.com/electron/asar/pull/61

update asar to fix https://github.com/electron/asar/pull/61

---

docs/api.md
mac.js
package.json
test/basic.js
test/fixtures/basic/package.json

Closes #213, #150
electron-builder tests passed as well.

use fs-extra copy instead of ncp

---

.travis.yml
NEWS.md
common.js
index.js
mac.js
package.json
readme.md
test/basic.js
test/util.js
test/win32.js
win32.js

Removes a polyfill module and lets us use template strings.

Drop Node < 4 support

---

NEWS.md
cli.js
common.js
docs/api.md
index.js
mac.js
test/basic.js
usage.txt

Consolidates `cache` and `strict-ssl` into the new `download` parameter, which is more or less passed directly to `electron-download` (similar to `osx-sign` and `version-string`). The original two parameters are now deprecated. This also lets us easily add sub-properties such as `mirror` (as requested in #316).
Depends on #319<del>, so [this](https://github.com/electron-userland/electron-packager/compare/drop-node-lt-4-support...malept:consolidate-download-options) might be a better diff to look at until it's merged</del>.
Closes #316.

Consolidate electron-download options

---

NEWS.md
docs/api.md
test/win32.js
usage.txt
win32.js

Also simplifies the implementation a bit (possibly depending on your point of view...), and makes the tests a little more comprehensive, making sure that passing strings to `version-string` actually works.

Remove deprecated version-string subproperties

---

.gitignore
.travis.yml
test/ci/before_install.sh
test/ci/dev_ca.cnf
test/config.json
test/mac.js
test/win32.js

Fixes part of #322.
@sethlu I've figured out how to get `codesign` working here, if you want I can adapt this method for `electron-osx-sign`.

Add support for OSX on Travis CI

---

package.json
readme.md
test/basic.js
test/ci/appveyor.yml
test/multitarget.js

Fixes part of #322.
This adds a devDependency (`is-admin`) because a test is dependent on whether a) it runs on Windows, and b) the test is running with elevated privileges, i.e., it can create symlinks.
I'm not sure if uploading code coverage to Coveralls is useful with Appveyor, just because it creates separate builds for each build in the matrix (and it doesn't execute as much code as Travis, because it's running on Windows).
@develar electron-builder's Appveyor tests run under the electron-userland org. Can I get access? (To the Appveyor org, not electron-builder.)

Appveyor CI support

---

NEWS.md
cli.js
common.js
test/basic.js

Moves CLI argument parsing code to the common module. This allows the CLI argument parsing code to be unit tested (of which, tests for some corner cases have been added).
Also uses `alias` for the deprecated `--strict-ssl` flag. This should remove the consistent deprecation message. <sup>[[1]](https://github.com/electron-userland/electron-packager/pull/320#discussion_r60160184) [[2]](https://github.com/electron-userland/electron-packager/pull/320#commitcomment-17173369)</sup>
My intention is to release 7.0.1 once this is merged.

CLI argument parsing code refactor

---

index.js

Previously, folders name “agit” or “bgit" would get ignored.

Escape dot in ".git" correctly

---

cli.js

Because of https://github.com/nodejs/node/issues/6456, in node@6 you don't (yet) see all of the usage text because the process exits before all was written out. This is a temporary fix.

temporary fix for node 6 stdio issue

---

NEWS.md
common.js
docs/api.md
test/basic.js
usage.txt

:wave: 
We distribute git in our app and git uses relative symlinks to refer to its main executable from some auxiliary executables.
Since `electron-packager` always dereference symlinks, this would end up blowing up the app bundle size by ~180MBs with tons of copies of `git`.
So it’d be great to be able to choose whether symlinks are dereferenced.

Add option for dereferencing symlinks

---

mac.js

Electron apps are big, so any time we can avoid copying the better. Renaming is faster so use it when we safely can.

Use fs.rename instead of fs.move when renaming Mac app

---

NEWS.md
common.js
docs/api.md
test/basic.js
usage.txt

This is a continuation of #353, but it is rebased against master, merges `asar-options` into `asar`, and adds tests.
It only enhances `asar` and deprecates `asar-unpack` and `asar-unpack-dir`, so only a minor version bump is required.
Closes #353.

Unify asar options

---

mac.js
test/mac.js

I rewrote a 150-line function into a 20-line function plus a 200-line class helper. More code, but also more readable. Something similar will probably happen to `win32.js`, although that code isn't nearly as complex.
Also, fixed a test for the Mac code that wasn't correct.

Refactor building the Mac app bundle

---

CONTRIBUTING.md
NEWS.md
docs/api.md
index.js
package.json
readme.md
test/basic.js
test/fixtures/basic-renamed-to-electron/index.html
test/fixtures/basic-renamed-to-electron/main.js
test/fixtures/basic-renamed-to-electron/package.json
test/index.js

A rename of `electron-prebuilt` to `electron` is in the works: https://github.com/electron-userland/electron-prebuilt/issues/160
Both`electron-prebuilt` and `electron` will be published in tandem through the end of 2016.
This PR updates `electron-packager` to add support for users of the `electron` package, while maintaining existing functionality for `electron-prebuilt`.
@kevinsawicki @jlord @zcbenz @iolsen

Add support for the new `electron` package name

---

index.js
test/basic.js

Related to https://github.com/electron-userland/electron-packager/issues/439.
Also, we don't need to check `!pkg`, because it will throw `module not found` error if no package.json file found.

Fix dir of getNameAndVersion for require package.json

---

NEWS.md
common.js
test/cli.js

Yes
Closes #386.
This uses a different approach from #386, in that it only handles typecasting for the CLI and not the API. Additionally, it assumes that `--out` without a value is the same as omitting `--out`.
CC: @sethlu
Added NEWS entry
Yes (see `test/cli.js`)
**Did the testsuite pass successfully on your local machine?**
Yes

CLI: ensure --out has either a string or null value

---

index.js
package.json

Cleanup PR for #445. Takes advantage of `get-package-info@0.1.0` to get the source prop that provided the inferred electron version without having to make two calls.
The inference tests passed for me but a couple codesign tests failed. I hope that's just my machine.

Remove unnecessary second get-package-json call

---

NEWS.md
index.js
package.json

Fixes https://github.com/electron-userland/electron-packager/issues/441
This brings `get-package-info` back into the mix, so directories are properly traversed for `package.json` files containing `electron` or `electron-prebuilt`. The work is broken up into two functions now to work around the [`resolve` issue](https://github.com/substack/node-resolve/pull/81) that causes an error to be thrown when a given set of props are not found.
cc @malept @kevinsawicki

fix version inference regression

---

common.js
docs/api.md
index.js
test/hooks.js

* Hook runs once your app dir has been copied to a temp dir
* No hook has no effect (install async callback)
* Generalized the afterExtract test to easily add an afterCopy test
The main use case for this hook is to run `electron-rebuild` or a simply `node-gyp` rebuild script against the **copied** `node_modules` folder.
TLDR: This will make rebuilding `node_modules` for Electron very easy now 👍 (Once I get around to hooking `electron-rebuild` into this)

Add a hook for afterCopy

---

test/basic.js

This seemed unneeded since the spec name is already logged by tape.
```
setup
infer test using `electron` package
start createInferElectronTest
```
/cc @zeke

Remove log statement at start of test infer electron test

---

docs/api.md
test/cli.js
test/mac.js
usage.txt

Adds documentation and an initial test for the `protocol`/`protocol-name` option.
Closes #121

Add protocol/protocol-name docs and test

---

test/index.js

Previously, if `npm install` on the fixtures failed or if Electron download failed, the tests would not fail.
This pull request adds error handling when either of those fails.

Handle errors setting up tests

---

NEWS.md
cli.js

Yes
If Electron Packager's CLI is run with an old version of Node, it will give a SyntaxError which is not intuitive to people what that means. This change (based on a suggestion by @MarshallOfSound in https://github.com/electron-userland/electron-packager/pull/445#issuecomment-239189295) gets rid of the SyntaxError, but tells the user exactly why the CLI will not run, before exiting with a non-zero status code. (Example output below.)
Yes (prior to this PR existing):
* [the NEWS file](https://github.com/electron-userland/electron-packager/bl …

Enforce minimum Node version in CLI

---

.gitignore
.travis.yml
NEWS.md
docs/api.md
index.js
mac.js
test/ci/before_install.sh
test/fixtures/basic/package.json
test/mac.js

This infers the `--app-version` from the `package.json` `version` property if it has not been passed in through the command line.
For an app using Electron `1.2.6` with a `package.json` version of `1.1.0`:
Before | After
--- | ---
cc pairing with @kevinsawicki @jlord 
Fixes #306

Infer --app-version from package.json

---

NEWS.md
mac.js
test/mac.js

Yes
Removes the suboption `osx-sign.binaries` if it is set and print a warning to that effect. See discussion in #285 and #286 for context.
CC: @sethlu 
Closes #285.
Not necessary, the docs specify which suboptions are supported.
Yes
Yes

Disallow setting osx-sign.binaries

---

NEWS.md
common.js
docs/api.md
test/asar.js
test/basic.js
test/cli.js
usage.txt

Yes
Removes:
* The `electron-download`-related options (`cache` and `strict-ssl`), deprecated in 7.0.0 (4/17)
* `asar-unpack` and `asar-unpack-dir` options, deprecated in 7.3.0 (7/10)
Removed docs about deprecated options and added NEWS entries
Removed tests related to the deprecated options
Yes

Remove deprecated options for asar & electron-download

---

NEWS.md
docs/api.md
test/win32.js
usage.txt
win32.js

Yes
Deprecates `version-string` in favor of `win32metadata`. `version-string` will be removed in a future major version.
Fixes #331.
Updated NEWS, API, & CLI docs.
Yes
Yes

Rename version-string option to win32metadata

---

NEWS.md
common.js
docs/api.md
linux.js
mac.js
package.json
readme.md
test/basic.js
test/mac.js
test/win32.js
win32.js

Yes
This fixes the problem where an Electron app name contains characters that are invalid in some target platform's filename. The most common case is [Node's scoped packages](https://docs.npmjs.com/misc/scope). The change utilizes the [`sanitize-filename`](https://www.npmjs.com/package/sanitize-filename) module to do all of the filename filtering.
Fixes #308.
I added notes to both `readme.md` and `docs/api.md` saying that invalid characters will be replaced with a hyphen.
I added tests to …

Remove special path characters from app name in filenames

---

package.json

- `asar@0.12.2`
- Fixed a regression where generating large `.asar` files could cause `Maximum call stack size exceeded` errors
- Upgraded to `minimatch@3.0.3` to address https://nodesecurity.io/advisories/minimatch_regular-expression-denial-of-service
- `rcedit@0.7.0`
- Fixed issue where callback was called with `string` instead of `Error` when command failed
- Improved error messages
- Fixed issues setting values on non-English and/or .NET binaries
I believe #53 can now be closed after this gets merged, several errors are mentioned in that issue that have now been addressed in `rcedit` such as missing `.ddl` errors, non-ASCII path issues, and others.
Closes #53

Upgrade rcedit and asar

---

NEWS.md
cli.js
docs/api.md
index.js
readme.md
test/basic.js
usage.txt

Yes
The defaults are the host's arch and platform values.
Fixes #36.
Updated NEWS, <ins>readme</ins>, API, & CLI docs. <del>I probably need to update the readme as well (have not done that yet).</del>
Changed the defaults test to test the new platform/arch defaults.
Yes

Add default values to arch and platform

---

package.json

Indeed
Upgrade `asar` to `0.12.3` which added support for multibyte characters in paths. Previously this would lead to errors when packaging/loading an app that included a file or folder with a multibyte character in its name.
N/A
N/A
Yes

Upgrade asar for multibyte character in path support

---

NEWS.md
common.js
docs/api.md
readme.md
test/basic.js
usage.txt

Yes
In both the CLI and API, `prune` defaults to `true` (the CLI is just more explicit about it in the code).
@zeke I know you assigned yourself to #35 but I had some time the other day to work on this.
Addresses #35. (Obviously, not the `asar` part.)
Fixes #235.
The CLI docs now mentions `--no-prune` instead of `--prune`. Also updated NEWS, the readme, and the API docs.
Updated the defaults test, added a test for prune=false. …

Default the prune option to true

---

common.js
ignore.js
index.js
test/ignore.js

Yes
First and foremost, this fixes a regression that was introduced in #455 - the ignores generated when the `out` option resolves to the current working directory were not having their basenames properly sanitized.
While I was in there, I also ES6ified the ignore code (including the tests) and refactored out all of the ignore-related code into its own file. The one downside to that is that I had to introduce a function-level require to one of the ignore functions, in order to avoid nonfunctional circular requires.
Not applicable
**Do your …

Sanitize ignores created when the output dir resolves to CWD

---

NEWS.md
common.js
docs/api.md
index.js
package.json
readme.md
targets.js
test/basic.js
test/multitarget.js
test/util.js
usage.txt

Yes
Electron has had Linux ARM support since 0.29.0, but I have been hesitant to merge any PRs for it until Electron properly tagged its downloads with the correct version of the ARM processor that it supports<sup>[1](#note-1)</sup>. In this case, ARMv7. Fortunately, this is now on the horizon.
However, according to the Electron PR, the properly named ARM builds will only be backported to versions >= 1.0.0. We will support Electron versions 0.29.0 and above by modifying the arguments passed to `electron-download` to use the old name when the Electron version is less than 1.0.0. This …

Add Linux ARMv7 support

---

test/basic.js
test/hooks.js
test/mac.js
test/multitarget.js
test/util.js
test/win32.js

Yes
* creates a new `util.packagerTest()`, which is a wrapper for `setup(); test(...); teardown();`
* Gets rid of a duplicate definition of `verifyPackageExistence()`
* Some ES6ifying during the process
Not applicable
Yes
Yes

DRY up some test code

---

NEWS.md
docs/api.md
ignore.js
test/ignore.js

Yes
Avoids the step of having to ignore `.o` files when signing the app for OSX/macOS (per the [Electron docs](https://github.com/electron/electron/blob/05043432ddb8e832d9541be94fc7f49e14a85092/docs/tutorial/mac-app-store-submission-guide.md#sign-native-modules)). Also ignore Windows `.obj` files for completeness.
@jlord @kevinsawicki @zeke do you see any potential issues with adding this regex to the default ignore list?
Yes
Yes
**Does the testsuite pass successfully on your local …

Add object files to default ignore patterns

---

NEWS.md
docs/api.md
test/basic.js
test/util.js

Yes
Exploring fixing the build failures introduced by #493, do not merge before 🍏 
Travis Mac workers are currently running out of memory while showing the download progress bar, this needs to be investigated upstream in `electron-download`/`nugget` but this pull request will try and work around it for now.
Yes
Yes
Yes

Fix Travis Mac builds

---

NEWS.md
test/win32.js
win32.js

Totes
Default the `build-version` option to the `app-version` when it is unspecified. This makes the Windows behavior consistent with the macOS defaulting behavior introduced in  #449.
Closes #498 
Yup
Yes
Yes

Default build version to app version  on Windows

---

docs/api.md
mac.js
test/mac.js
usage.txt

fix typo in extend plist
added object params support for the "extend-info"
```
packager({
...
'extend-info': {
ElectronTeamId: 'RJ883jd299'
}
});
```
no, My English is not enough for writing docs
yes
yes

fix typo in extend-info and add support object params

---

mac.js
package.json
test/mac.js

Hi @malept, I'm only posting this PR for now. Further tests may be required before eventually merging this I think. Hopefully a stable version of `electron-osx-sign` could be released later this week.

Upgrade electron-osx-sign to 0.4.1

---

NEWS.md
common.js
docs/api.md
index.js
mac.js
test/basic.js
usage.txt

Yes
When set, this prevents printing Electron Packager specific warnings and informational messages to the console. This does *not* disable errors.
CC: @MarshallOfSound mostly because we can get rid of that console monkeypatch workaround in [Electron Forge](https://github.com/MarshallOfSound/electron-forge).
Fixes #538.
Yes (CLI usage, API docs).
Yes.
Yes.

Add quiet option

---

CONTRIBUTING.md
issue_template.md
pull_request_template.md

* Explicitly mention the community Code of Conduct. This has been implied since we're part of the Electron ecosystem, but I'd rather make it explicit.
* Add a section to the contributing docs about the Electron community forums.
* Update the issue/PR templates to mention the CoC and also use checkboxes.

[RFC] Mention the community CoC & update issue/PR templates

---

common.js
mac.js

Make it way more obvious that warning messages are not error messages. (see: #586 & duplicates)

Prepend all warning messages with 'WARNING:'

---

common.js
docs/api.md
ignore.js
index.js
test/ignore.js
test/util.js

Fixes #548. (The weird Docker bug.)
Also, put the building of the temporary directory path into its own function.
CC: @MarshallOfSound

Ignore the generated temporary directory on Linux

---

.travis.yml

* <del>The changes have sufficient test coverage (not applicable).
Run but don't require a CI pass for Node 5 + OSX.
Workaround for #598.

Ignore Travis Node 5 + OSX worker due to strange problem

---

readme.md

This changes the default recommendation to use Packager to build bundles for a given target platform on the same host platform.

Infer platform/arch in readme instead of using --all

---

NEWS.md
common.js
docs/api.md
index.js
mac.js
test/basic.js
test/cli.js
test/mac.js
test/win32.js
win32.js

- Does it need any tests?
This fixes #325.

Use camelCase identifiers in the JS API

---

index.js
test/basic.js

This will be a style error in the next version of standard (v10).

Always return an Error or null in node-style callbacks

---

common.js
docs/api.md
ignore.js
index.js
infer.js
test/basic.js
test/fixtures/infer-electron-prebuilt-compile/package.json
test/fixtures/infer-non-specific-electron-prebuilt-compile/package.json
test/index.js
test/infer.js

Refactored the code so that all of the option inferring from `package.json` is in its own file (same with its tests). Adds limited support for inferring the Electron version of projects using `electron-prebuilt-compile`.
Of interest to @paulcbetts: I found out that the `main` key in `electron-prebuilt-compile` isn't pointing to a real file, so I can't do `resolve('electron-prebuilt-compile')` like I can with the others. I wonder if it's worth having `resolve` parity with the canonical `electron` module moving forward?
Of interest to @MarshallOfSound: This could get rid of the "Forge needs to explicitly specify the Electron version" code in the package stage.

Limited support for inferring electron-prebuilt-compile

---

.travis.yml
NEWS.md
common.js
docs/api.md
package.json
prune.js
test/basic.js
test/ci/before_install.sh
test/index.js
test/prune.js
usage.txt

* [?] The changes are appropriately documented (if applicable).
* [?] The changes have sufficient test coverage (if applicable).
This PR introduces "package-manager" option.
It is a replacement of #614, and it tries to implement the spec defined in #515.
It can parse 'nom', 'yarn' as package-manager option.
When other package manager is specified, a warning message is shown.
This PR does not include the code below.
1. modification of usage.txt 
2. unit test
Thanks in advance for reading this message.
Fixes #518.
Addresses #515.

Add package-manager option

---

docs/api.md
package.json
test/win32.js
usage.txt
win32.js

As per http://layer0.authentise.com/electron-and-uac-on-windows.html, have added the ability for rcedit.exe to modify the requested execution level, so that the Electron app can have administrator privileges.  https://github.com/dmascord/rcedit and https://github.com/dmascord/node-rcedit have been updated appropriately, and a pull request has been issued for them too.
Fixes #197.

Add support for updating the application manifest and requested execution level for Windows targets

---

.travis.yml
test/ci/before_install.sh

* ~~The changes are appropriately documented~~ (not applicable).
* ~~The changes have sufficient test coverage~~ (not applicable).
* ~~The testsuite passes successfully on my local machine~~ (not applicable).
`npm@5` (strangely, just on OSX) doesn't install modules correctly for some reason. Example:
https://travis-ci.org/electron-userland/electron-packager/jobs/239192709
Closes #598.

Travis: Re-enable Node 5/OSX, Downgrade to npm@4 for Node 8/OSX

---

NEWS.md
docs/api.md
index.js
test/basic.js
usage.txt

Drop `version` since `electronVersion` support has been out for a while. Will probably add `--version` back (that works like a normal `--version` param) in version 10.
Fixes #154.

Remove deprecated version option

---

NEWS.md
docs/api.md
index.js
infer.js
package.json
test/fixtures/infer-win32metadata/package.json
test/infer.js
test/win32.js
usage.txt
win32.js

Infer win32metadata from package.json/top-level options

---

NEWS.md
docs/api.md
test/win32.js
usage.txt
win32.js

Pretty self-explanatory. Please use `win32metadata` instead (which was added in version 8.0.0, in September 2016).

Remove deprecated version-string option

---

NEWS.md
common.js
docs/api.md
index.js
package.json
test/basic.js
test/cli.js

They have been replaced with camelCased names. CLI options remain the same (it uses `camelize` to convert the names).
This is a continuation of #580.

Remove support for hyphenated option names via JS API

---

NEWS.md
common.js
docs/api.md
index.js
test/hooks.js

Added an `afterPrune` hook for handling changes that affect ASAR logic in the `prune` step.

Add afterPrune hook

---

NEWS.md
prune.js
test/prune.js

`yarn install` by default resurrects the `.bin` folders which breaks ASAR support as they are symlinked files.  This will stop `yarn` creating those folders

Do not add .bin folders when pruning

---

NEWS.md
docs/api.md
package.json
prune.js
test/prune.js

This should help avoid package manager specific pruning issues as we now walk the dependency tree manually.

Add option to use custom pruning module

---

NEWS.md
docs/api.md
readme.md
targets.js
test/targets.js
test/util.js
usage.txt

With https://github.com/electron/electron/pull/10219 merged, ARM64 support is likely to be official starting with the Electron 1.8 release series. This adds basic official support for the arch, plus adds it to the platform/arch combinations when `all` is true or `platform=linux` and `arch=all` is set, and the specified version of Electron is 1.8.0 or above.

Add ARM64 support

---

NEWS.md
infer.js
test/infer.js

Don't use `parse-author` when it's already an Object.
Fixes #718.

Fix inferring `win32metadata.CompanyName` when author is an Object

---

NEWS.md
common.js
test/cli.js
usage.txt

* Deprecate/warn when using nonstandard CLI options. I'm doing this because I think I'm going to move towards yargs-parser (which is more maintained and looks like it will let me get rid of some of the CLI handling code)
* Update some CLI docs for clarity

Clean up CLI options/docs

---

targets.js
test/targets.js

Adds two API functions in `target.js`:
* `hostArch`, which is the same function as `electronHostArch` in Electron Forge and is used internally as well
* `allOfficialArchsForPlatformAndVersion`, made specifically for Forge (https://github.com/electron-userland/electron-forge/pull/320). It might be nice to eventually use it internally, but it would take a nontrivial refactor.

Add target arch API

---

common.js
package.json

`minimist` is unmaintained, `yargs-parser` is maintained and also compatible with `minimist`'s API. It also has its own camel-case implementation so we can get rid of `camelize` as well.

Replace minimist & camelize with yargs-parser

---

docs/api.md
linux.js
mac.js
platform.js
test/basic.js
test/mac.js
test/win32.js
usage.txt
win32.js

Adds the `executableName` option (`--executable-name` in CLI) which allows to set the executable name, which defaults to `name` but does not affect the `.app` name.
Example:
```javascript
const packager = require('electron-packager')
packager({
name: 'App Name',
executableName: 'app-name',
platform: 'all'
})
```
On Windows, the Electron binary will be `app-name.exe`. On Linux, the Electron binary will be `app-name`. On macOS, the app is `App Name.app` and the binary inside it is `App Name.app/Contents/MacOS/app-name`.
----
Fixes #745.

Add option to set the executable name separate from the app name

---

prune.js
test/prune.js

Don't create yarn.lock when pruning with Yarn

---

package.json
targets.js
test/targets.js

Several versions of Node for `armv7l` incorrectly identify as `arm_version: '6'`.
See: nodejs/node#4531 and related.

Fix ARM detection on armv7l Node

---

docs/api.md

When useing `electron-packager` pragmatically for OS X packaging, `protocol` and `protocolName` option will not work for setting OS X URL protocol schemes.
Instead use `protocols` option described in [mac.js#L34](https://github.com/electron-userland/electron-packager/blob/3ce4907d7645578e1ba24754d86ed531b0671112/mac.js#L34), [test/darwin.js#L262](https://github.com/electron-userland/electron-packager/blob/3ce4907d7645578e1ba24754d86ed531b0671112/test/darwin.js#L262) and used in [mac.js#L168](https://github.com/electron-userland/electron-packager/blob/31e1e98634f453a566bb424d04c220230ffdd238/mac.js#L168) will produce the right plist file.
Closes #643.

Fix protocols API docs

---

index.js
test/basic.js

Fix overwrite when default platform/arch are used

---

.travis.yml
ignore.js
package.json
readme.md
test/ci/appveyor.yml

codecov works with both Travis CI *and* AppVeyor, so certain Windows-specific code can be covered.

Replace coveralls with codecov

---

NEWS.md
docs/api.md
readme.md
targets.js
test/_util.js
test/targets.js
usage.txt

This arch is available with official Electron releases starting with [Electron 1.8.2-beta.5](https://github.com/electron/electron/releases/tag/v1.8.2-beta.5).
This is a breaking change, since the behavior of the `all` option changes.

Add support for official MIPS64EL arch on Linux

---

cli.js

`--help` has never been a defined command line argument, it always just checked for the presence of `opts.dir`.
Fixes #802.

Send usage text to stdout if --help specified

---

mac.js
test/_setup.js
test/mas.js

Adjusts the config for `Electron Login Helper.app`, if it exists.
@MarshallOfSound could you take a look and make sure this is what you're supposed to do, since I don't have a Mac?

Add MAS Login Helper support

---

common.js
docs/api.md
hooks.js
index.js
platform.js
test/hooks.js

Adds `serialHooks(hooks)` (ported from Electron Forge), which allows a user to run hooks serially instead of in parallel (which was added in v10.0.0 due to `Promise.all`).
Closes #812.

Add a utility function to execute hooks serially

---

cli.js
docs/api.md
index.js

Just so everyone's clear: when callback-style syntax is removed from Electron Packager, folks will have to add [`nodeify`](https://npm.im/nodeify) to their dependencies if they want to keep using that syntax.

Deprecate the callback version of the packager API

---

cli.js
common.js
index.js
usage.txt

Re-add `--version`, but this time make it have the behavior that most other CLIs have. If it is given a value, it will print a warning about possible other related flags.

Add --version to print out Packager/Node versions, target platform/arch

---

targets.js
test/targets.js

This fixes `all: true` and `platform:linux` + `arch: all` cases as well.
See also: https://github.com/electron/electronjs.org/pull/1252

Prevent trying to download mips64el arch for Electron 2.x

---

prune.js
test/prune.js

Better detection of node modules when pruning

---

.gitignore
prune.js
test/prune.js

* The changes are appropriately documented (not applicable).
Fixes #888.
I've tested with the minimal testcase in the related bug.

Prune user-namespaced modules

---

docs/api.md
mac.js
test/darwin.js
usage.txt

Refs: https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_app

feat: add darwinDarkModeSupport option to support mojave dark mode for older Electron versions

---

mac.js
test/_util.js
test/darwin.js

Don't try to modify helper plists, etc., [if they don't exist](https://github.com/electron/electron/pull/14436).
Tested manually with the latest 4.0 nightly. (I'm not using that in the tests because the testsuite downloads way too many Electron versions as it is.)

Don't handle EH/NP Helpers if they don't exist

---

targets.js

Remove the deprecated API from bffd6838d911c9bea75aa1b414b417e5aa872365

Remove deprecated target arch API

---

docs/api.md
index.js
package.json
readme.md

Removes callback-style support (use `nodeify` if you need that still), and adds an `async`/`await` example to the API docs.

Drop callback support

---

.travis.yml
test/ci/appveyor.yml
test/ci/before_install.sh

Use Travis CI's (currently in beta) Windows support for x64 tests. Keep the x86 tests on AppVeyor.
Also update Linux CI to use Ubuntu 16.04.

Use Travis CI for some Windows CI

---

ignore.js
test/ignore.js

This happens when both the dir and the out dir are relative to the current working directory.
Fixes #918.

Ensure relative out dirs are correctly ignored when copying

---

infer.js
test/fixtures/infer-electron-nightly/node_modules/electron-nightly/package.json
test/fixtures/infer-electron-nightly/package.json
test/infer.js

Nightlies were [moved to `electron-nightly`](https://github.com/electron/electron/pull/15938).

Add support for inferring version from Electron nightlies

---

infer.js
test/fixtures/infer-invalid-non-specific-electron-prebuilt-compile/package.json
test/fixtures/infer-non-specific-electron-prebuilt-compile/node_modules/electron-prebuilt-compile/package.json
test/infer.js

In `electron-prebuilt-compile` 1.6.5, a `main` file was added, so we can use the normal way of inferring the version instead of using the workaround.
Fixes #909.
CC: @jacobq

Handle inferring electron-prebuilt-compile versions better

---

targets.js
test/targets.js

See:
* https://electronjs.org/blog/linux-32bit-support
* https://github.com/electron/electron/issues/16407

fix(targets): Linux/ia32 is no longer supported for Electron >= 4

---

package.json
test/_setup.js
test/darwin.js

With the Node 8 changes, `mz` is no longer necessary. One less dependency!

Drop mz for util.promisify

---

CONTRIBUTING.md
package.json
src/index.js

`extract-zip` is effectively unmaintained, and we're already using `cross-zip` in Forge (for different reasons).
`cross-zip` also has fewer Node dependencies, although the tradeoff is that [on Windows it requires a certain version of .NET Framework & Powershell](https://github.com/feross/cross-zip/blob/v2.1.5/README.md#windows-users).

Replace extract-zip with cross-zip

---

docs/api.md
package.json
src/cli.js
src/ignore.js
test/ignore.js
usage.txt

Uses [`junk`](https://github.com/sindresorhus/junk) to determine which are considered "system junk files".

feat: ignore system junk files by default

---

CONTRIBUTING.md
docs/api.md
package.json
src/cli.js
src/download.js
src/targets.js
test/_setup.js
test/basic.js
test/cli.js
test/targets.js
usage.txt

BREAKING CHANGE: The download options are completely different.
Depends on:
* https://github.com/electron/get/pull/94 (debug support)
* https://github.com/electron/get/pull/93, somewhat (docs support, need to link to a place where all of the options are enumerated)

 feat: convert from electron-download to @electron/get 

---

package.json
src/targets.js
test/targets.js

Reverts https://github.com/electron-userland/electron-packager/pull/957 and requires `@electron/get@^1.3.0`, as `@electron/get` has the warning instead of Packager.

Linux/ia32 warning moved from Packager to @electron/get

---

readme.md

This project has been officially declared as an "open open source" project for the past 3 years, although it's informally been like that for much longer. Unfortunately, with events like the [`event-stream` incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident) happening, we need to rethink how we want to handle contributions. This is an important package in the Electron ecosystem, and it should be protected as such. Ultimately, I've decided to revert back to a more traditional maintainership model: if you'd like to be a maintainer of this project, you'll need to show that you'll do the work necessary for the role, whether it's triaging issues, submitting features/bug fixes, or enhancing the documentation.

Remove section from README about 'Open Open Source'

---

src/index.js
src/unzip.js

fix(unzip): warn Windows 7 users of the unzip dependency

---

src/mac.js
test/_setup.js
test/darwin.js

Adds support for the new `Electron Helper (Renderer).app` and `Electron Helper (Plugin).app` helper bundles 👍

fix: support Electron v6 helpers

---

package.json
test/cli.js

New major version of `eslint-plugin-ava`, only one thing needed fixing.

chore(deps-dev): upgrade eslint-plugin-ava to ^8

---

package.json
test/infer.js
test/win32.js

chore(deps-dev): upgrade eslint-config-standard to ^14

---

src/mac.js
test/darwin.js

The `CFBundleExecutable` value was wrong as we were overwriting `this.helperPlist` for every helper.  Now we don't and now the values are correct.  There are even tests and stuff
Fixes #1045.

fix: ensure that CFBundleExecutable and friends are correct for helper apps

---

src/cli.js
test/cli.js

Fix osx-sign can't get correctly sub properties, just use `osx-sign` arg instead of `osxSign`.
For `yargs-parser`, use camel case of args is meaning the subprops will be also converted to camel case, but it will break the [`osx-sign`](https://github.com/electron/electron-osx-sign/blob/master/sign.js#L307) usage like `entitlements-inherit`.

fix: send the properly formatted options from the CLI to electron-osx-sign

---

NEWS.md
docs/api.md
src/mac.js
test/darwin.js
usage.txt

Adds a convenience option to set usage descriptions for the macOS store, on `darwin`/`mas` targets.
Reference: https://github.com/electron/electron/pull/19871#pullrequestreview-278011263

feat: add usageDescription option for darwin/mas targets

---

NEWS.md
README.md
src/targets.js
test/_util.js
test/targets.js

Official win32/arm64 builds were added in Electron [6.0.8](https://github.com/electron/electron/releases/tag/v6.0.8).
Fixes #1052.

feat: add support for win32/arm64 official builds

---

test/_setup.js
test/ci/before_install.sh
test/win32.js

[`wine` was removed from Homebrew-core](https://github.com/Homebrew/homebrew-core/pull/46556) due to macOS 10.15 incompatibility. Trying to install it from Homebrew casks results in CI hanging. So, disable win32 tests on macOS CI until the situation is resolved.

test(macOS): disable win32 target testing

---

src/cli.js

Don't expect users to set the environment variable `ELECTRON_GET_USE_PROXY=1` if they need to use a proxy.

fix: always initialize proxy support when running the CLI

---

src/infer.js
test/infer.js

Also, handle a missing inferred app version better.
Fixes #1072.

fix(infer): make the error message clearer when infer cannot find a package.json file

---

.github/workflows/canary.yml

This is a feature I brought up at the Electron Maintainers Summit in NYC. A canary runs daily (via GitHub Actions) that:
1. Checks out `electron-quick-start`
2. Replaces `electron` with `electron-nightly`
3. Uses Electron Packager from the `master` branch to build an Electron app for all platforms and arches
This is meant to find any strange problems in Electron nightlies when customizing and bundling apps.

test: add nightly canary

---

src/win32.js
test/win32.js

node-rcedit 2.1.0 added support for wine64. Since Packager rewrites the error message to be more human-readable, it needs to take into account the new binary name possibility.

fix(win32): handle missing wine64 binaries in addition to wine

---

src/cli.js
test/cli.js

fix: emit a warning if --osx-sign and a sub-property are specified in the CLI

---

src/index.js

randomize testPath in symlink test to allow parallel compilation with the --all option
* [] The changes are appropriately documented (if applicable).
* [] The changes have sufficient test coverage (if applicable).
* [] The testsuite passes successfully on my local machine (if applicable).
Hi, on my linux machine (8 cores), the -all option does not create mas and darwin packages:
```
$ uname -a
Linux AC-SV-611 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ npx electron-packager --version
Electron Packager 14.1.1
Node v12.13.0
Host Operating system: linux 5.3.0-24-generic (x64)
$ npx electron-packager --all  --overwrite=true  compiled/build/ EduAnat2
Packaging app for platform win32 ia32 using electron v7.1.3 …
```

fix: make symlink test robust to parallel packaging

---

src/mac.js
src/platform.js
test/darwin.js

Noticed in #1100. It generates a warning if the icon specified isn't found.

fix(mac): don't fail if the icon path given doesn't exist

---

docs/api.md

docs: add a link to the Electron docs for darwinDarkModeSupport

---

package.json
test/_util.js

Removes a few transitive `devDependencies`.

test: replace tempy with fs.mkdtemp

---

src/win32.js

I noticed that the human-friendly message wasn't getting printed out on a Linux install sans wine.

fix(win32): correctly catch missing wine exceptions

---

README.md
package.json
src/unzip.js
test/index.js
test/unzip.js

Closes #1029 
Fixes #1120 
Closes #1082

refactor: replace cross-zip with extract-zip

---

src/index.d.ts
test/index.test-d.ts

fix(typescript): ensure OsxNotarizeOptions definition contains credentials

---

test/_util.js
test/targets.js

Somehow I missed this when merging #1168.

test: fix allPlatformArchCombosCount given new win32/arm64 combo

---

.gitignore
src/copy-filter.js
test/copy-filter.js

Added `package-lock.json` and `yarn.lock` to the default ignored file regex.

fix(copy-filter): add package manager lockfiles to default ignore

---

src/targets.js
test/targets.js

Fixes #1190 
The behavior exhibited by semver in that issue is apparently [intended behavior](https://github.com/npm/node-semver#prerelease-tags), but I don't think it makes much sense in this context, so I've set the option to disable it, which allows ARM64 builds to work as intended.

fix(targets): allow checking official builds against prerelease versions

---

package.json

Reverts electron/electron-packager#1216
Fixes #1217

revert: "chore(deps-dev): bump typedoc from 0.19.2 to 0.20.20"

---

src/index.d.ts

For some reason, `extraResource` didn't link to `process.resourcesPath`, which is how you'd reference packaged files in the resources path to begin with.

docs: link to process.resourcesPath with extraResource

---

README.md
package.json
src/win32.js
test/win32.js

This upgrade adds two features:
* Support for running rcedit on darwin/arm64
* Support for running rcedit on WSL without Wine installed

feat: upgrade to rcedit@^3.0.1

---

.github/ISSUE_TEMPLATE/config.yml
README.md
SUPPORT.md

Folks with questions about Electron Packager should go to the Discord server.

docs: advertise the Discord server

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/config.yml
.github/pull_request_template.md
.github/workflows/docs.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
NEWS.md
README.md
SUPPORT.md
docs/faq.md
src/infer.js
usage.txt

The default branch has changed from `master` to `main`, update references as appropriate (`electron/electron` has also changed, so change those references as well).

chore: replace references to the default branch

---

.github/ISSUE_TEMPLATE/config.yml

`discord.gg` redirects to the ds landing page, this should be `discord.gg/electron` as written in the other places

docs(issue-template): fix invite link to discord server

---

NEWS.md
src/index.d.ts
src/mac.js
test/darwin.js

For apps that want to customize the Helper app plist files they currently have to do so in an `afterCopy` or other out-of-band step.  Adding `extendHelperInfo` to match `extendInfo` makes it much easier to extend these plist files.
This PR also ensures we set `CFBundleShortVersionString` and `CFBundleVersion` on helper plists.

feat: allow extension of helper app plists with extendHelperInfo

---

.eslintrc.typescript.js
package.json
src/index.d.ts
src/mac.js
test/darwin.js

electron-notarize 1.1.0 added a new mode (using the new `notarytool` binary) which caused `validateAuthorizationArgs` to break.
Update notarization support so that the `tool: notarytool` option works with TypeScript.
Since the module handles its own validation, I'm removing it from this module.
Fixes #1277.

fix(mac): compatibility with electron-notarize@^1.1.0

---

package.json
src/mac.js
src/platform.js
test/darwin.js

Refs https://github.com/electron/electron/pull/30667
Small addition to automatically insert the new (currently optional) `ElectronAsarIntegrity` block into your Info.plist

feat: automatically insert ElectronAsarIntegrity into Info.plist

---

README.md
package.json
src/index.d.ts
src/index.js
src/targets.js
src/universal.js
test/_setup.js
test/_util.js
test/basic.js
test/targets.js
usage.txt

As in title, this integrates @electron/universal into packager by intercepting package requests for "universal" and then building arm64 / x64 separately behind the scenes and stitching them together.

feat: integrate @electron/universal

---

src/index.d.ts
src/universal.js

As in title, building in parallel results in some `node-gyp` weirdness and the type for `HookFunction` was wrong

fix: build universal packages sequentially and allow hooks to return error in TS

---

.circleci/config.yml
.github/workflows/canary.yml
.github/workflows/docs.yml
package.json

Electron Packager is still using Node 10 and Node 12; Node 12 was deprecated in April 2022. This PR requires at least Node 14 LTS, and bumps the automated tests to test on newer versions of Node (14, 16, 18 as opposed to 10, 12, 14).
NB: Since this would be a breaking change, we may want to merge other fixes first and do another release before merging this one.

feat!: upgrade Node.js to 14 LTS

---

.circleci/config.yml

CI is failing on Node 10 because multiple packages no longer support it (fs-extra, get, etc).
This PR eliminates that job so we can do a stable release. After which, we'll move to Node 14 as a minimum version number.

chore: remove node 10 job

---

package.json

Aligns packager with electron core, and fixes a got issue. This PR bumps @electron/get to 2.0.0.
I did not mark this change as a breaking change, because the required version of Node is already 14 and higher; the new minimum version needed for @electron/get is 12.20.55.

build: bump @electron/get to 2.0.0

---

src/cli.js

Fixes #1404
Common is not imported in the cli.js.
so builds are failing.

fix: properly import info logger

---

package.json

It looks upgrading typedoc broke the docs because of breaking API changes between minor versions.
```
$ node test/ci/build_docs.js
error Tried to set an option (includeDeclarations) that was not declared.
error Tried to set an option (mode) that was not declared.
error Unable to find any entry points. Make sure TypeDoc can find your tsconfig
Could not generate API documentation from TypeScript definition!
error Command failed with exit code 1.
```
https://github.com/electron/electron-packager/actions/runs/3046234742/jobs/4908793618
cc @ckerr

chore: Revert "chore: bump typedoc from 0.19.2 to 0.23.14 (#1416)"

---

NEWS.md
package.json
src/index.d.ts
src/mac.js
test/cli.js
test/darwin.js
test/index.test-d.ts
usage.txt

BREAKING CHANGE: This changes the accepted options for the `osxSign` option.
TODO:

feat!: upgrade electron-osx-sign to @electron/osx-sign

---

NEWS.md
package.json
src/index.d.ts
src/platform.js

Purely cosmetic rename of the `asar` package

refactor: migrate from asar to @electron/asar

---

NEWS.md
package.json
src/index.d.ts
src/mac.js
usage.txt

Purely cosmetic rename of the `electron-notarize` package

refactor: migrate from electron-notarize to @electron/notarize

---

src/index.d.ts
src/platform.js
test/hooks.js
test/index.test-d.ts

This PR partially addresses #509 with the following new lifecycle methods: `afterAsar`, `afterComplete`, `afterCopyExtraResources`, `beforeAsar`, `beforeCopy`, `beforeCopyExtraResources`. There's definitely room for improvement, so any feedback is welcome.

feat: New lifecycle hooks: afterAsar, afterComplete, afterCopyExtraResources, beforeAsar, beforeCopy, beforeCopyExtraResources

---

NEWS.md
src/index.d.ts
src/index.js
test/hooks.js
test/index.test-d.ts

Ref: https://github.com/electron/forge/pull/3006

feat: add new afterFinalizePackageTargets hook

---

src/index.js
src/platform.js

Packager didn't use unique staging / temp directories so running packager twice with similar targets would cause issues.

fix: allow packaging twice simultaneously

---

README.md
src/index.d.ts

Just a couple of minor capitalization fixes.
References:
- https://github.com/npm/cli#is-it-npm-or-npm-or-npm
- https://developer.apple.com/xcode/

chore: proper npm and Xcode capitalization

---

src/cli.js
src/common.js
src/copy-filter.js
src/mac.js
src/platform.js
src/prune.js
src/targets.js
test/basic.js

As in title, we weren't passing `opts/args.quiet` into the common warning and info helpers in a bunch of cases which leads to unwanted logs all over the place 🙃

fix: ensure logs are quiet when quiet flag is passed

---

src/targets.js
test/targets.js

Compare the assets of [19.0.0-alpha.5](https://github.com/electron/electron/releases/tag/v19.0.0-alpha.5) with [19.0.0-beta.1](https://github.com/electron/electron/releases/tag/v19.0.0-beta.1).
Fixes #1447

fix(targets): linux/ia32 official support was removed in Electron 19

---

src/index.d.ts

Linking to other APIs in TypeDoc can be done through two ways: `[[ target ]]` or `{@link target}`.
The `[[target]]` syntax is TypeDoc-specific (see https://github.com/TypeStrong/typedoc/issues/1317) while `{@link target}` is a TSDoc standard (see [spec](https://tsdoc.org/pages/tags/link/)).
Two reasons for migrating over:
* TSDoc has deprecated the `[[target]]` syntax and is fully removing it in v0.24 (see [CHANGELOG](https://github.com/TypeStrong/typedoc/blob/3830f9650ec7d2bc5e7b53bd28898f23fc6c5590/CHANGELOG.md#v0230-2022-06-26)).
* As of TypeScript 4.3, `{@link target}` is used for smarter editor intellisense (see [release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#editor-support-for-link-tags)).

docs: use tsdoc `@link` syntax for .d.ts comments

---

package.json
yarn.lock

This resolution forces a deep dev dep of `ava` to use a newer `got`

build: update got to clean up yarn audit

---

README.md

Updates links for repos which have moved. Also adds a status badge for the “electron-nightly canary” scheduled workflow.

docs: update links in README.md

---

.github/workflows/canary.yml

The default branch for `electron/electron-quick-start` has moved to `main` and that is causing some [GHA workflow failures](https://github.com/electron/electron-packager/actions/runs/4869795755/jobs/8684739009#step:2:55) for the canary workflow.

build: update electron/electron-quick-start branch to main

---

usage.txt

In https://github.com/electron/electron-packager/pull/1346, we added support for the `--arch=universal` flag, but never properly documented CLI usage of the associated `OsxUniversalOptions`.
For the future, we should also document the `@electron/universal` options better. We currently have no docs around these flags outside of the source code.
I tested the syntax by running the following command:
```
DEBUG=electron-universal npx electron-packager . --arch=universal --osx-universal.mergeASARs="true"
```
From here, I was able to confirm that the Universal package was receiving the options properly:
```
electron-universal making a universal app with options {
mergeASARs: 'true',
x64AppPath: '/var/folders/wy/zjrnw32x2496ydq6ps7vljfc0000gp/T/electron-packager/electro …
```

fix(docs): add `osx-universal` flag to usage.txt

---

README.md

**Summarize your changes:** A few formatting changes, as well as a note on dot notation for nested CLI flags.

docs: clarify CLI usage

---

src/prune.js

If `electron-nightly` is installed in `dependencies` by accident, we want to prune it.

fix: prune `electron-nightly` even if in dependencies

---

.github/workflows/canary.yml

Our `electron-nightly` canary job runs the latest nightly version of Electron against the `main` branch of Electron Packager.
This job has been busted for a while, and it seems because `--arch=all` does not work on macOS ever since we. This is a separate issue, but for now, let's just create a single `--arch=universal` job so that we can unblock the canary.
See **https://github.com/electron/electron-packager/pull/1539/commits/c7a3088fc7493c7922f3ac1a7ef35a17bdd7bfa6** for that job running on this PR.

ci: make canary run `--arch=universal` on macOS

---

.circleci/config.yml
test/_setup.js

Fixes #1421.
Our `test-linux` suite has had a very poor 52% success rate according to CircleCI insights. Each one of the Linux test suites seems to fail about 1/5 of the time.
| Job Name        | Total Credits | P95 Duration (seconds) | Runs | Success Rate |
|-----------------|---------------|------------------------|------|--------------|
| "test-linux-14" | 517           | 227                    | 17   | 0.82         |
| "test-linux-16" | 539           | 220                    | 19   | 0.79         |
| "test-linux-18" | 542           | 271                    | 16   | 0.81         |
| "test-mac"      | 3031          | 329                    | 15   | 1            |
| "test-windows"  | 1974          | 272                    | 17   | 0.88         |
The observed error was always the …

test: set `cacheRoot` on checksum download

---

.github/workflows/docs.yml

Picks up [some upstream fixes](https://github.com/malept/github-action-gh-pages/compare/main...dsanders11:github-action-gh-pages:2023) and uses the built-in `GITHUB_TOKEN` to do the `git push`, [as documented here](https://github.com/actions/checkout#push-a-commit-using-the-built-in-token).
Ideally will get the fixes upstreamed to `malept/github-action-gh-pages` and we can switch back to that.

ci: fix publish documentation workflow

---

package.json
yarn.lock

This PR bumps osx-sign to use 1.0.5 as a min version, to fix an issue with signing entitlements.

fix(osx-sign): bump osx-sign to 1.0.5

---

NEWS.md
package.json

chore: 17.1.2

---

.github/workflows/canary.yml
.github/workflows/docs.yml

Get off of Node.js 14 since that's EOL and just use the current LTS to avoid the upgrade treadmill for these workflows, as it's low risk.

ci: bump Node.js version for workflows

---

.github/workflows/canary.yml
.github/workflows/docs.yml

Follow-up to #1569, which apparently broke the publish docs workflow. This repo has a `yarn.lock` but the workflows were still using `npm` commands, and after bumping the Node.js version apparently those `npm` commands were modifying `yarn.lock` leading to an error. 🤔 So switch to using `yarn` commands.

ci: use yarn in workflows

---

.github/workflows/canary.yml

Partially reverts #1570, the canary build needs to use `npm` when running commands in the checkout of `electron/electron-quick-start`.

ci: use npm in canary workflow

---

src/platform.js

**Summarize your changes:** Fix: Don't use app name when creating temporary directories, ensuring that npm scripts expecting paths without spaces will work fine.

fix: Create tmp directory without using app name

---

src/common.js
test/basic.js

chore: use console.info for info logging

---

NEWS.md
src/mac.js
test/darwin.js

Currently there is no way to know that signing on osx failed other than reading the output. This adds an option `continueOnError` (defaults to current behavior, `true`) one can set to fail the build if there was an error while signing the app.

feat: Add `osxSign.continueOnError` option

---

src/index.d.ts
src/mac.js
test/darwin.js
test/index.test-d.ts

BREAKING CHANGE: remove support for the `tool` option in `osxNotarize`, meaning `notaryTool` will always be used and users will no longer be able to provide `tool: 'legacy'` (see https://github.com/electron/notarize/pull/141). This also removes the `NotarizeLegacyOptions` and `OsxNotarizeOptions` types because they're no longer necessary.

chore!: remove support for the legacy notarization tool

---

src/universal.js

Not sure why we didn't do this in the first place, but this should be faster than doing them one at a time

fix: x64/arm64 parallel builds for universal

---

.circleci/config.yml
package.json
test/ci/build_docs.js
yarn.lock

Updated ~because of the nice dark theme~ to work with Typescript 5.2:

chore: update TypeDoc

---

.circleci/config.yml
README.md
package.json

`--ignore-engines` is no longer needed after #1608, and removing it revealed that we actually need `>= 16.13`. I think it changed as a result of #1593. It's probably only a dev dependency forcing it, but we can't differentiate between the minimum engine version for dev versus prod so we usually peg them to whichever is higher. In this case it doesn't really make a practical difference, users should probably be using the latest minor release anyway.

chore: update minimum Node.js version to 16.13

---

CODE_OF_CONDUCT.md

We have [the org-wide `CODE_OF_CONDUCT.md`](https://github.com/electron/.github/blob/main/CODE_OF_CONDUCT.md) which is inherited by all repos, so this one is redundant.

chore: remove redundant CODE_OF_CONDUCT.md

---

README.md
docs/faq.md
src/infer.ts
usage.txt

Updates broken documentation links from the TypeDoc upgrade (#1614).
Fixes #1631.

fix: update broken documentation links

---

.gitignore

The shim introduced in #1641 causes [an issue with the docs publish workflow](https://github.com/electron/packager/actions/runs/7263804212/job/19789924601) since it is seen as an uncommitted file. Adding it to `.gitignore` fixes that.

build: add shim to gitignore

---

src/cli.ts
src/types.ts
test/cli.js
usage.txt

This default value has been broken for a while, as `@electron/get` expects the `rejectUnauthorized` property inside the `downloadOptions` object, not as a top-level option. This PR is just updating the docs to reflect the current behavior.

chore: remove broken default option

---

.github/ISSUE_TEMPLATE/config.yml

chore: update discord invite link

---

.github/workflows/docs.yml

`malept/github-action-gh-pages` stages the changes to commit, and `dsanders11/github-app-commit-action` commits them.

ci: make signed commits when publishing docs

---

.circleci/config.yml
README.md
package.json
src/rcedit.ts
src/resedit.ts
src/types.ts
src/win32.ts
test/_setup.js
test/ci/before_install.sh
test/win32.js
yarn.lock

This re-implements _everythin_ that `rcedit` used to do with a native binary using a purely JS implementation of resource editing.
This is required to drop the package-on-platform requirements of the win32 target, it also will make it easier to add asar integrity windows manifest values in the future.

feat: remove dependency on rcedit to allow x-platform exe resource modding

---

src/resedit.ts
src/win32.ts

This is currently targeting my "remove rcedit" branch so that the diff is small and makes sense.
Pretty straight forward, sets the right asar integrity resource when packaging for windows.

feat: set asar integrity resource on windows packages

---

README.md

`npx` should reference the new module not the old one

docs: fix npx usage to be scoped module

---

src/types.ts

fix(types): HookFunction.platform should use TargetPlatform

---

src/win32.ts

Fixing windows-sign does not work due to `appDirectory` missing.

fix: appDireactory missing for windows-sign options

---

.github/dependabot.yml

Dependabot currently attempts to upgrade all dependencies, even if not necessary for security reasons.
I modified our `dependabot.yml` to align with [Forge's](https://github.com/electron/forge/blob/main/.github/dependabot.yml).

chore: reduce number of dependabot PRs

---

src/platform.ts
test/darwin.js

If you are building an app with a prebuilt ASAR archive, we should still include the ASAR integrity hash in the app bundle.

fix: include asar integrity when using --prebuilt-asar

---

src/mac.ts
src/platform.ts

After the `resedit` change cross-building windows on macOS is suddenly a Thing People Can Do so we need to make sure we use windows path separators for the asar integrity manifest when targeting the windows platform.
Fixes #1780

fix: use target platform path separators for asar integrity keys

---

.circleci/config.yml

Adds CI for the latest LTS version of Node.js

ci: test node 22

---

CONTRIBUTING.md

Follow-up to #1784 to remove references in `CONTRIBUTING.md` to the old CI systems.

docs: remove references to CircleCI and AppVeyor

---

package.json

Follow-up to #1792 that moves `husky install` from the `postinstall` script (wrong spot) to `prepare`.

build: move husky from postinstall to prepare script

---

.github/workflows/docs.yml
.github/workflows/test.yml
package.json

The existing docs workflow no longer works, so replace it with the generic workflow we've been using for repos when we do the Node.js 22 upgrade. That way if we put out another release before we get around to the Node.js 22 upgrade, the docs will publish properly.

ci: update docs workflow

---

src/icon-composer.ts

Follow up to #1806, this PR corrects how the os versioning is checked when trying to use the new Icon Composer icon feature.

fix: fix semver check for icon composer

---

package.json
test/packager.spec.ts
vitest.config.ts

Fast follow-up because I think `main` is failing. This aligns with what our previous ava test timeout was set to.

test: use 120s timeout globally

---

.github/workflows/docs.yml

We use a different folder for the API documentation flow so the last couple uploads have only uploaded the actual `/docs` folder. I think this fixes it: https://github.com/electron/packager/pull/1807

ci: upload `/typedoc` folder to packages.electronjs.org

---

src/cli.ts
src/platform.ts
src/types.ts
test/cli.spec.ts

BREAKING CHANGE: defaults to `derefSymlinks: true` if the value isn't explicitly defined.
This PR also removes the second layer of logic that defaults this value via the CLI (instead specifying it in the core API).

feat!: default `derefSymlinks` to `true`

---

.github/workflows/test.yml

Removed `main` branch restriction for pull request trigger
Helps when stacking PRs on top of each other. :)

ci: make CI run on any PR

---

src/common.ts
src/copy-filter.ts
src/download.ts
src/infer.ts
src/mac.ts
src/packager.ts
src/platform.ts
src/targets.ts
src/types.ts
src/universal.ts
src/win32.ts
test/common.spec.ts
test/copy-filter.spec.ts
test/hooks.spec.ts
test/infer.spec.ts
test/packager.spec.ts
test/resedit.spec.ts
test/targets.spec.ts
test/utils.ts

This PR attempts to simplify how we handle the `Options` interface in Electron Packager.
There are two main problems to address:
1. External: the `TargetArch` and `TargetPlatform` types used in the `Options` interface are aliases to `string`. This is because we accept `string` values for custom mirrors of Electron, so any string const value passed in gets swallowed by the resulting type.
```ts
// the following types are functionally equivalent in TS!
type TargetArch1 = 'arch1' | 'arch2' | string;
type TargetArch2 = string;
```
2. Internal: the `Options` interface defines what options can be passed in as values, but also serves as the interface that we use to pass to the final packaging function. Along the way, many optional properties in `Options` are inferred and mutated. This approach …

refactor: improve `Options` types

---

.github/workflows/canary.yml

We accidentally broke the canary workflow in #1821 because we only check out `electron/minimal-repro` there, and that repo doesn't have a `.nvmrc` file.
It probably also makes sense for the canary workflow to be using the latest Node.js anyway to catch any potential errors.

ci: fix setup-node in canary workflow
